export type Genre =
    | "Acid blues"
    | "Acid breaks"
    | "Acid house"
    | "Acid jazz"
    | "Acid rock"
    | "Acid techno"
    | "Acid trance"
    | "Acidcore"
    | "Adult contemporary"
    | "Afrobeat"
    | "Afropop"
    | "Afrotrap"
    | "Aguinaldo"
    | "Allaoui"
    | "Amapiano"
    | "Ambient"
    | "Ambient house"
    | "Ambient jungle"
    | "Ambient techno"
    | "Americana"
    | "Anarcho-punk"
    | "Anti-folk"
    | "Apala"
    | "Arena rock"
    | "Ars antiqua"
    | "Ars nova"
    | "Art punk"
    | "Art rock"
    | "Ars subtilior"
    | "Austropop"
    | "Avant-funk"
    | "Avant-garde jazz"
    | "Avant-prog"
    | "Avanthop"
    | "Axé"
    | "Bachata"
    | "Bachatango"
    | "Baggy"
    | "Baguala"
    | "Baião"
    | "Baila"
    | "Baile funk"
    | "Bakersfield sound"
    | "Balearic beat"
    | "Balearic trance"
    | "Ballade"
    | "Ballet"
    | "Baltimore club"
    | "Bambuco"
    | "Barbershop"
    | "Bass music"
    | "Bassline"
    | "Batucada"
    | "Bay Area thrash metal"
    | "Beat"
    | "Beatbox"
    | "Beiguan"
    | "Benga"
    | "Bebop"
    | "Berceuse"
    | "Big band"
    | "Big beat"
    | "Big room house"
    | "Biguine"
    | "Bikutsi"
    | "Black metal"
    | "Black metal dépressif"
    | "Black metal norvégien"
    | "Black metal symphonique"
    | "Bluegrass"
    | "Blues"
    | "Blues africain"
    | "Blues électrique"
    | "Blues rock"
    | "Blues touareg"
    | "Blues traditionnel"
    | "Boléro"
    | "Bongo Flava"
    | "Boogaloo"
    | "Boogie-woogie"
    | "Bossa nova"
    | "Bounce music"
    | "Brass band"
    | "Breakbeat"
    | "Breakbeat hardcore"
    | "Breakcore"
    | "Britpop"
    | "Broken beat"
    | "Brutal death metal"
    | "Bubblegum pop"
    | "Bubblegum dance"
    | "C86"
    | "C-pop"
    | "Calypso"
    | "Cantopop"
    | "Cello rock"
    | "Cha-cha-cha"
    | "Chaâbi algérien"
    | "Chaâbi marocain"
    | "Changüí"
    | "Chanson française"
    | "Chant grégorien"
    | "Chicago blues"
    | "Chicago house"
    | "Chill-out"
    | "Chillstep"
    | "Chillwave"
    | "Chiptune"
    | "City pop"
    | "Classic rag"
    | "Cloud rap"
    | "Cold wave"
    | "College rock"
    | "Combat folk"
    | "Complextro"
    | "Concerto"
    | "Conte musical"
    | "Contradanza"
    | "Cool jazz"
    | "Country"
    | "Country alternative"
    | "Country folk"
    | "Country néo traditionnelle"
    | "Country pop"
    | "Country rap"
    | "Country rock"
    | "Country soul"
    | "Coupé-décalé"
    | "Cowpunk"
    | "Crossover"
    | "Crossover thrash"
    | "Crunk"
    | "Crunk'n'b"
    | "Crunkcore"
    | "Crust punk"
    | "Cumbia"
    | "D-beat"
    | "Dance"
    | "Dance-pop"
    | "Dance-punk"
    | "Dance-rock"
    | "Dancehall"
    | "Dangdut"
    | "Danzón"
    | "Dark ambient"
    | "Dark jazz"
    | "Dark metal"
    | "Dark psytrance"
    | "Dark wave"
    | "Dark wave néo-classique"
    | "Darkcore"
    | "Darkstep"
    | "Death-doom"
    | "Death metal"
    | "Death metal mélodique"
    | "Death metal technique"
    | "Death 'n' roll"
    | "Death rock"
    | "Deathcore"
    | "Deathcountry"
    | "Deathgrind"
    | "Deep house"
    | "Deepkho"
    | "Delta blues"
    | "Detroit blues"
    | "Digital hardcore"
    | "Dirty South"
    | "Disco"
    | "Disco house"
    | "Disco polo"
    | "Diva house"
    | "Dixieland"
    | "Djent"
    | "Doo-wop"
    | "Doom metal"
    | "Downtempo"
    | "Dream pop"
    | "Dream trance"
    | "Drill"
    | "Drill and bass"
    | "Drone"
    | "Drum and bass"
    | "Drumfunk"
    | "Drumstep"
    | "Dub"
    | "Dub poetry"
    | "Dub techno"
    | "Dubstep"
    | "Dubstyle"
    | "Dunedin sound"
    | "Dutch house"
    | "Early hardcore"
    | "Easycore"
    | "Electro"
    | "Electro house"
    | "Electro swing"
    | "Electroclash"
    | "Électro-industriel"
    | "Electronic body music"
    | "Electronic"
    | "Electronic dance music"
    | "Electronica"
    | "Electronicore"
    | "Emo"
    | "Emo pop"
    | "Éthio-jazz"
    | "Ethno-jazz"
    | "Euro disco"
    | "Eurobeat"
    | "Eurodance"
    | "Europop"
    | "Experimental"
    | "Extratone"
    | "Fado"
    | "Fanfare"
    | "Fidget house"
    | "Filin"
    | "Flamenco"
    | "Folk"
    | "Folk metal"
    | "Folk progressif"
    | "Folk psychédélique"
    | "Folk rock"
    | "Folktronica"
    | "Freakbeat"
    | "Free jazz"
    | "Freeform hardcore"
    | "Freestyle"
    | "French touch"
    | "Frenchcore"
    | "Fun-punk"
    | "Funk"
    | "Funk rock"
    | "Funk metal"
    | "Funktronica"
    | "Funky house"
    | "Future bass"
    | "Future garage"
    | "Future house"
    | "G-funk"
    | "Gabber"
    | "Gaelic punk"
    | "Gangsta rap"
    | "Garage house"
    | "Garage punk"
    | "Garage rock"
    | "Geek rock"
    | "Ghetto house"
    | "Ghettotech"
    | "Glam metal"
    | "Glam punk"
    | "Glam rock"
    | "Glitch"
    | "Glitch-hop"
    | "Goregrind"
    | "Gospel"
    | "Gospel blues"
    | "Gothabilly"
    | "Gqom"
    | "Grebo"
    | "Grime"
    | "Grindcore"
    | "Grindie"
    | "Groove metal"
    | "Grunge"
    | "Guajira"
    | "Guaracha"
    | "Gypsy punk"
    | "Handsup"
    | "Happy gabber"
    | "Happy hardcore"
    | "Hard bop"
    | "Hard house"
    | "Hard rock"
    | "Hard trance"
    | "Hardbag"
    | "Hardbass"
    | "Hardcore chrétien"
    | "Hardcore mélodique"
    | "Hardstep"
    | "Hardstyle"
    | "Hardtechno"
    | "Heartland rock"
    | "Heavy metal"
    | "Heavy metal traditionnel"
    | "Hi-NRG"
    | "Highlife"
    | "Hip-hop"
    | "Hip-hop alternatif"
    | "Hip-hop australien"
    | "Hip-hop chrétien"
    | "Hip-hop expérimental"
    | "Hip-hop old-school"
    | "Hip-hop orchestral"
    | "Hip-hop psychédélique"
    | "Hip-hop sud-coréen"
    | "Hip-house"
    | "Hiplife"
    | "Hipster-hop"
    | "Honky tonk"
    | "Horror punk"
    | "Horrorcore"
    | "House"
    | "House progressive"
    | "Hybrid trap"
    | "Hyperpop"
    | "Illbient"
    | "Indie"
    | "Indie dance"
    | "Indie folk"
    | "Indie pop"
    | "Industrial hardcore"
    | "Intelligent dance music"
    | "Italo dance"
    | "Italo disco"
    | "Italo house"
    | "J-core"
    | "J-pop"
    | "J-rock"
    | "Jangle pop"
    | "Jazz"
    | "Jazz afro-cubain"
    | "Jazz blues"
    | "Jazz-funk"
    | "Jazz fusion"
    | "Jazz manouche"
    | "Jazz modal"
    | "Jazz Nouvelle-Orléans"
    | "Jazz punk"
    | "Jazz rap"
    | "Jazz vocal"
    | "Jazz West Coast"
    | "Jazzstep"
    | "Jersey"
    | "Jump blues"
    | "Jump-up"
    | "Jumpstyle"
    | "Jungle"
    | "K-pop"
    | "Kaneka"
    | "Kansas City blues"
    | "Kasékò"
    | "Kawaii metal"
    | "Kizomba"
    | "Klezmer"
    | "Kompa"
    | "Krautrock"
    | "Kuduro"
    | "Kwaito"
    | "Latin house"
    | "Latin jazz"
    | "Latin metal"
    | "Lento violento"
    | "Léròl"
    | "Liquid funk"
    | "Livetronica"
    | "Lo-fi"
    | "Logobi"
    | "Louisiana blues"
    | "Lounge"
    | "Luk thung"
    | "Madchester"
    | "Mainstream jazz"
    | "Mainstream hardcore"
    | "Makina"
    | "Makossa"
    | "Maloya"
    | "Mambo"
    | "Mandopop"
    | "Mangue beat"
    | "Marche"
    | "Mashup"
    | "Math rock"
    | "Mathcore"
    | "Mbalax"
    | "Medieval rock"
    | "Memphis blues"
    | "Merengue"
    | "Merenhouse"
    | "Metal alternatif"
    | "Metal avant-gardiste"
    | "Metal celtique"
    | "Metal chrétien"
    | "Metal extrême"
    | "Metal gothique"
    | "Metal industriel"
    | "Metal néo-classique"
    | "Metal oriental"
    | "Metal progressif"
    | "Metal symphonique"
    | "Metalcore"
    | "Metalcore mélodique"
    | "Mgodro"
    | "Miami bass"
    | "Microhouse"
    | "Midwest rap"
    | "Milonga"
    | "Minimal"
    | "Minneapolis sound"
    | "Moombahcore"
    | "Moombahton"
    | "Mozambique"
    | "Murga"
    | "Musette"
    | "Música popular brasileira"
    | "Musique acoustique"
    | "Musique aléatoire"
    | "Musique alternative"
    | "Musique ancienne"
    | "Musique arabo-andalouse"
    | "Musique baroque"
    | "Musique bretonne"
    | "Musique bruitiste"
    | "Musique cadienne"
    | "Musique celtique"
    | "Musique chrétienne contemporaine"
    | "Musique classique"
    | "Musique concrète"
    | "Musique cubaine"
    | "Musique de jeu vidéo"
    | "Musique de variétés"
    | "Musiques du monde"
    | "Musique électroacoustique"
    | "Musique électronique"
    | "Musique émergente"
    | "Musique expérimentale"
    | "Musique gothique"
    | "Musique industrielle"
    | "Musique instrumentale"
    | "Musique irlandaise"
    | "Musique latine"
    | "Musique LGBT"
    | "Musique minimaliste"
    | "Musique mixte"
    | "Musique post-industrielle"
    | "Musique progressive"
    | "Musique romantique"
    | "Musique sérielle"
    | "Musique spectrale"
    | "Nardcore"
    | "Nashville sound"
    | "National socialist black metal"
    | "Nederpop"
    | "Negro spiritual"
    | "Néo-bop"
    | "Néo-classicisme"
    | "Neo-psychedelia"
    | "Neo soul"
    | "Néo-trad"
    | "Néofolk"
    | "Nerdcore"
    | "Neue Deutsche Härte"
    | "Neue Deutsche Welle"
    | "Neurofunk"
    | "New age"
    | "New beat"
    | "New jack swing"
    | "New prog"
    | "New wave"
    | "New wave of American heavy metal"
    | "New wave of British heavy metal"
    | "New York blues"
    | "New York hardcore"
    | "Nightcore"
    | "Nintendocore"
    | "Nocturne"
    | "Nouveau flamenco"
    | "No wave"
    | "Noise pop"
    | "Noise rock"
    | "Northern soul"
    | "Nu-disco"
    | "Nu-NRG"
    | "Nu jazz"
    | "Nu metal"
    | "Nueva trova"
    | "Oi!"
    | "Old-time"
    | "Opéra"
    | "Opéra-rock"
    | "Oratorio"
    | "Outlaw country"
    | "Pachanga"
    | "Paisley Underground"
    | "Palm-wine music"
    | "Paso doble"
    | "Philadelphia soul"
    | "Phonk"
    | "Piano blues"
    | "Piano rock"
    | "Piano stride"
    | "Piedmont blues"
    | "Pirate metal"
    | "Polonaise"
    | "Pop"
    | "Pop alternative"
    | "Pop baroque"
    | "Pop latino"
    | "Pop metal"
    | "Pop progressive"
    | "Pop psychédélique"
    | "Pop punk"
    | "Pop-rap"
    | "Pop rock"
    | "Pornogrind"
    | "Post-bop"
    | "Post-disco"
    | "Post-grunge"
    | "Post-hardcore"
    | "Post-metal"
    | "Post-punk"
    | "Post-rock"
    | "Power ballad"
    | "Power metal"
    | "Power pop"
    | "Powerviolence"
    | "Prélude"
    | "Progressive psytrance"
    | "Protopunk"
    | "Psychobilly"
    | "Pub rock"
    | "Punk blues"
    | "Punk celtique"
    | "Punk chrétien"
    | "Punk folk"
    | "Punk hardcore"
    | "Punk rock"
    | "Punta rock"
    | "Punto guajiro"
    | "Paghjella"
    | "Queercore"
    | "Quiet storm"
    | "Rabiz"
    | "Raga rock"
    | "Ragga"
    | "Ragtime"
    | "Raï"
    | "Raï'n'B"
    | "Rap"
    | "Rap East Coast"
    | "Rap hardcore"
    | "Rap metal"
    | "Rap politique"
    | "Rap rock"
    | "Rap West Coast"
    | "Rapcore"
    | "Rave"
    | "Rawstyle"
    | "Rebetiko"
    | "Red dirt"
    | "Reggae"
    | "Reggae fusion"
    | "Reggaeton"
    | "Rhapsodie"
    | "Rhythm and blues"
    | "Riot grrrl"
    | "R&B"
    | "R&B alternatif"
    | "R&B contemporain"
    | "Rock"
    | "Rock alternatif"
    | "Rock alternatif latino"
    | "Rock anticommuniste"
    | "Rock argentin"
    | "Rock brésilien"
    | "Rock canadien"
    | "Rock celtique"
    | "Rock chilien"
    | "Rock chinois"
    | "Rock chrétien"
    | "Rock communiste"
    | "Rock électronique"
    | "Rock expérimental"
    | "Rock gothique"
    | "Rock identitaire français"
    | "Rock in opposition"
    | "Rock indépendant"
    | "Rock industriel"
    | "Rock instrumental"
    | "Rock 'n' roll"
    | "Rock néo-progressif"
    | "Rock progressif"
    | "Rock progressif espagnol"
    | "Rock progressif français"
    | "Rock progressif italien"
    | "Rock psychédélique"
    | "Rock sudiste"
    | "Rock suédois"
    | "Rock symphonique"
    | "Rock turc"
    | "Rock wagnérien"
    | "Rockabilly"
    | "Rocksteady"
    | "Rondo"
    | "Roots rock"
    | "Rumba"
    | "Rumba catalane"
    | "Rumba congolaise"
    | "Rumba flamenca"
    | "Sadcore"
    | "Saint Louis blues"
    | "Salegy"
    | "Salsa"
    | "Salsa-ragga"
    | "Salsaton"
    | "Samba"
    | "Samba funk"
    | "Samba jazz"
    | "Samba rock"
    | "Sambass"
    | "Scherzo"
    | "Schlager"
    | "Schranz"
    | "Screamo"
    | "Séga"
    | "Seggae"
    | "Semba"
    | "Shibuya-kei"
    | "Shock rock"
    | "Shoegazing"
    | "Ska"
    | "Ska-jazz"
    | "Skacore"
    | "Ska punk"
    | "Skate punk"
    | "Skiffle"
    | "Slam"
    | "Slow"
    | "Slow fox"
    | "Slowcore"
    | "Sludge metal"
    | "Smooth jazz"
    | "Snap"
    | "Soca"
    | "Soft rock"
    | "Son cubain"
    | "Sonate"
    | "Songo"
    | "Sophisti-pop"
    | "Soukous"
    | "Soul"
    | "Soul blues"
    | "Soul jazz"
    | "Soul progressive"
    | "Soul psychédélique"
    | "Southern gospel"
    | "Southern soul"
    | "Space age pop"
    | "Space rock"
    | "Speed garage"
    | "Speed metal"
    | "Speedcore"
    | "Splittercore"
    | "Stoner rock"
    | "Street punk"
    | "Sunshine pop"
    | "Surf"
    | "Swamp blues"
    | "Swamp pop"
    | "Swing"
    | "Symphonie"
    | "Synthpop"
    | "Synthpunk"
    | "Synthwave"
    | "T-pop"
    | "Tango"
    | "Tango nuevo"
    | "Taqwacore"
    | "Tarentelle"
    | "Tech house"
    | "Tech trance"
    | "Techno"
    | "Techno de Détroit"
    | "Techno hardcore"
    | "Techno minimale"
    | "Techstep"
    | "Tecno-brega"
    | "Tecno rumba"
    | "Teen pop"
    | "Terrorcore"
    | "Texas blues"
    | "Thrash metal"
    | "Thrash metal allemand"
    | "Thrashcore"
    | "Timba"
    | "Toccata"
    | "Trallpunk"
    | "Trance"
    | "Trance Goa"
    | "Trance psychédélique"
    | "Trance vocale"
    | "Trap"
    | "Tribal house"
    | "Tribe"
    | "Trip hop"
    | "Tropical house"
    | "Tropipop"
    | "Tumba francesa"
    | "Twarab"
    | "Twee pop"
    | "UK garage"
    | "UK hardcore"
    | "Unblack metal"
    | "Uplifting trance"
    | "uptempo"
    | "Vaporwave"
    | "Viking metal"
    | "Visual kei"
    | "Vocal house"
    | "West Coast blues"
    | "Western Swing"
    | "Witch house"
    | "Wizard rock"
    | "Wonky"
    | "Wonky pop"
    | "World music"
    | "Yéla"
    | "Yéyé"
    | "Youth crew"
    | "Zarico"
    | "Zeuhl"
    | "Ziglibithy"
    | "Zouglou"
    | "Zouk"
    | "Zumba"
    | "2-step garage"
    | "2 tone";
;